export default {
  pagejson: {
    groupName: "page",
    name: "page",
    implement: "neit",
    id: "#",
    text: "root",
    type: "nfreescenecabin",
    version: "1.0",
    attributes: {
      attr1: "value1",
      attr3: "value3",
      attr4: "value4",
      attr5: "value5",
      hotKeys: [],
      initMethod: "generateDataB",
      xttr1: "xttr1",
    },
    children: [
      {
        groupName: "nflex",
        name: "ncolflex",
        implement: "mouseX",
        text: "NColFlex",
        id: "ncolflex_ixFGWm",
        type: "ncolflex",
        version: "1.0",
        attributes: {
          id: "ncolflex_ixFGWm",
          height: "100%",
          flexBasic: "fill",
          hidden: false,
          hotKeys: [],
        },
        children: [
          {
            groupName: "nflex",
            name: "ncolflex",
            implement: "mouseX",
            text: "NColFlex",
            id: "ncolflex_sxkmBs",
            type: "ncolflex",
            version: "1.0",
            attributes: {
              id: "ncolflex_sxkmBs",
              height: "100%",
              flexBasic: "need",
              hidden: false,
              hotKeys: [],
            },
            children: [
              {
                groupName: "nform",
                name: "nform",
                implement: "mouseX",
                text: "NForm",
                id: "piinfo",
                type: "nform",
                version: "1.0",
                attributes: {
                  id: "piinfo",
                  readonly: false,
                  itemSpan: 8,
                  itemLabelSpan: 8,
                  itemValueSpan: 16,
                  colon: true,
                  flexBasic: "need",
                  hidden: false,
                },
                children: [
                  {
                    groupName: "nform",
                    name: "NStringInput",
                    implement: "mouseX",
                    text: "NStringInput",
                    id: "NStringInput_lurdin",
                    type: "nformNStringInput",
                    version: "1.0",
                    attributes: {
                      id: "NStringInput_lurdin",
                      name: "piid",
                      label: "流程实例编号",
                      inputMaxLength: -1,
                      autoComplete: true,
                      readonly: true,
                      required: false,
                      hidden: false,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontColor: "rgba(0, 0, 0, 0.85)",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                      prefix: false,
                      suffix: false,
                    },
                  },
                  {
                    groupName: "nform",
                    name: "NSingleSelect",
                    implement: "mouseX",
                    text: "NSingleSelect",
                    id: "NSingleSelect_CmoSXj",
                    type: "nformNSingleSelect",
                    version: "1.0",
                    attributes: {
                      id: "NSingleSelect_CmoSXj",
                      name: "status",
                      label: "运行状态",
                      readonly: true,
                      required: false,
                      hidden: false,
                      codeType: "jsoncode",
                      codeValue:
                        '[{"value": 1, "content": "运行中"},{"value": 0, "content": "结束"},{"value": 2, "content": "流程未开启"}] ',
                      allowClear: true,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontColor: "rgba(0, 0, 0, 0.85)",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                  {
                    groupName: "nform",
                    name: "NButtons",
                    implement: "mouseX",
                    text: "NButtons",
                    id: "NButtons_QicCxj",
                    type: "nformNButtons",
                    version: "1.0",
                    attributes: {
                      id: "NButtons_QicCxj",
                      align: "center",
                    },
                    children: [
                      {
                        groupName: "nform",
                        name: "NButton",
                        implement: "mouseX",
                        text: "NButton",
                        id: "NButton_zzOxjV",
                        type: "nformNButton",
                        version: "1.0",
                        attributes: {
                          id: "NButton_zzOxjV",
                          label: "手动触发执行",
                          authId: "",
                          title: "",
                          iconId: "",
                          iconColor: "",
                          size: "middle",
                          type: "primary",
                          danger: false,
                          ghost: false,
                          disabled: false,
                          hidden: false,
                          onClick: "runPI",
                        },
                      },
                      {
                        groupName: "nform",
                        name: "NButton",
                        implement: "mouseX",
                        text: "NButton",
                        id: "NButton_XJxZQQ",
                        type: "nformNButton",
                        version: "1.0",
                        attributes: {
                          id: "NButton_XJxZQQ",
                          label: "刷新状态",
                          authId: "",
                          title: "",
                          iconId: "",
                          iconColor: "",
                          size: "middle",
                          type: "primary",
                          danger: false,
                          ghost: false,
                          disabled: false,
                          hidden: false,
                          onClick: "generateData",
                        },
                      },
                    ],
                  },
                  {
                    groupName: "nform",
                    name: "NNextLine",
                    implement: "mouseX",
                    text: "NNextLine",
                    id: "NNextLine_GFwKoI",
                    type: "nformNNextLine",
                    version: "1.0",
                    attributes: {
                      id: "NNextLine_GFwKoI",
                    },
                  },
                  {
                    groupName: "nform",
                    name: "NDateInput",
                    implement: "mouseX",
                    text: "NDateInput",
                    id: "NDateInput_BqPtdq",
                    type: "nformNDateInput",
                    version: "1.0",
                    attributes: {
                      id: "NDateInput_BqPtdq",
                      name: "end_time",
                      label: "结束时间",
                      readonly: true,
                      required: false,
                      hidden: false,
                      format: "YYYY-MM-DD HH:mm:ss.SSS",
                      sourceFormat: "YYYY-MM-DD HH:mm:ss.SSS",
                      labelAlign: "right",
                      valueAlign: "center",
                      fontColor: "rgba(0, 0, 0, 0.85)",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                  {
                    groupName: "nform",
                    name: "NDateInput",
                    implement: "mouseX",
                    text: "NDateInput",
                    id: "NDateInput_WvINVo",
                    type: "nformNDateInput",
                    version: "1.0",
                    attributes: {
                      id: "NDateInput_WvINVo",
                      name: "start_time",
                      label: "开始时间",
                      readonly: true,
                      required: false,
                      hidden: false,
                      format: "YYYY-MM-DD HH:mm:ss.SSS",
                      sourceFormat: "YYYY-MM-DD HH:mm:ss.SSS",
                      labelAlign: "right",
                      valueAlign: "center",
                      fontColor: "rgba(0, 0, 0, 0.85)",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                ],
              },
              {
                groupName: "ntitle",
                name: "ntitle",
                implement: "mouseX",
                text: "NTitle",
                id: "ntitle_GscUNU",
                type: "ntitle",
                version: "1.0",
                attributes: {
                  id: "ntitle_GscUNU",
                  iconId: "hawkprocess",
                  showIcon: true,
                  text: "流程运行详情",
                  textUnderline: false,
                  textOblique: false,
                  flexBasic: "need",
                  hidden: false,
                },
              },
              {
                text: "NTitle",
                version: "1.0",
                implement: "mouseX",
                name: "ntitle",
                type: "ntitle",
                icon: "标题栏",
                groupName: "ntitle",
                id: "ntitle_AqFmMl",
                attributes: {
                  id: "ntitle_AqFmMl",
                  showIcon: true,
                  text: "布局内元素插入",
                  textUnderline: false,
                  textOblique: false,
                  flexBasic: "need",
                  hidden: false,
                },
              },
            ],
          },
          {
            text: "NColFlex",
            version: "1.0",
            implement: "mouseX",
            name: "ncolflex",
            type: "ncolflex",
            icon: "纵向分布",
            groupName: "nflex",
            id: "ncolflex_gUtCdM",
            attributes: {
              id: "ncolflex_gUtCdM",
              height: "100%",
              flexBasic: "fill",
              hidden: false,
              hotKeys: [],
            },
            children: [
              {
                text: "NTitle",
                version: "1.0",
                implement: "mouseX",
                name: "ntitle",
                type: "ntitle",
                icon: "标题栏",
                groupName: "ntitle",
                id: "ntitle_WimIjP",
                attributes: {
                  id: "ntitle_WimIjP",
                  showIcon: true,
                  text: "布局整体插入",
                  textUnderline: false,
                  textOblique: false,
                  flexBasic: "need",
                  hidden: false,
                },
              },
            ],
          },
          {
            text: "NRowFlex",
            version: "1.0",
            implement: "mouseX",
            name: "nrowflex",
            type: "nrowflex",
            icon: "横向分布",
            groupName: "nflex",
            id: "nrowflex_tGVWkK",
            attributes: {
              id: "nrowflex_tGVWkK",
              height: "100%",
              flexBasic: "fill",
              hidden: false,
              hotKeys: [],
            },
            children: [
              {
                text: "NForm",
                version: "1.0",
                implement: "mouseX",
                name: "nform",
                type: "nform",
                icon: "表单整体",
                groupName: "nform",
                id: "nform_hERIAC",
                attributes: {
                  id: "nform_hERIAC",
                  readonly: false,
                  itemSpan: 8,
                  itemLabelSpan: 8,
                  itemValueSpan: 16,
                  colon: true,
                  flexBasic: "need",
                  hidden: false,
                },
                children: [
                  {
                    text: "NStringInput",
                    name: "NStringInput",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNStringInput",
                    groupName: "nform",
                    id: "NStringInput_Kpbgov",
                    attributes: {
                      id: "NStringInput_Kpbgov",
                      name: "NStringInput_Kpbgov",
                      label: "姓名",
                      inputMaxLength: -1,
                      autoComplete: true,
                      readonly: false,
                      required: false,
                      hidden: false,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                      prefix: false,
                      suffix: false,
                    },
                  },
                  {
                    text: "NNumberInput",
                    name: "NNumberInput",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNNumberInput",
                    groupName: "nform",
                    id: "NNumberInput_BHdsjF",
                    attributes: {
                      id: "NNumberInput_BHdsjF",
                      name: "NNumberInput_BHdsjF",
                      label: "年龄",
                      inputMaxLength: -1,
                      readonly: false,
                      required: false,
                      hidden: false,
                      thousandsSeparator: true,
                      precision: "-1",
                      percentage: false,
                      labelAlign: "right",
                      valueAlign: "right",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                      prefix: false,
                      suffix: false,
                    },
                  },
                  {
                    text: "NSingleSelect",
                    name: "NSingleSelect",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNSingleSelect",
                    groupName: "nform",
                    id: "NSingleSelect_jgdgiu",
                    attributes: {
                      id: "NSingleSelect_jgdgiu",
                      name: "NSingleSelect_jgdgiu",
                      label: "学历",
                      readonly: false,
                      required: false,
                      hidden: false,
                      codeType: "syscode",
                      allowClear: true,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                ],
              },
              {
                text: "NForm",
                version: "1.0",
                implement: "mouseX",
                name: "nform",
                type: "nform",
                icon: "表单整体",
                groupName: "nform",
                id: "nform_wSMomO",
                attributes: {
                  id: "nform_wSMomO",
                  readonly: false,
                  itemSpan: 8,
                  itemLabelSpan: 8,
                  itemValueSpan: 16,
                  colon: true,
                  flexBasic: "need",
                  hidden: false,
                },
                children: [
                  {
                    text: "NPassword",
                    name: "NPassword",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNPassword",
                    groupName: "nform",
                    id: "NPassword_fZnkdP",
                    attributes: {
                      id: "NPassword_fZnkdP",
                      name: "NPassword_fZnkdP",
                      label: "密码",
                      inputMaxLength: -1,
                      readonly: false,
                      required: false,
                      hidden: false,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                  {
                    text: "NDateInput",
                    name: "NDateInput",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNDateInput",
                    groupName: "nform",
                    id: "NDateInput_YCIwil",
                    attributes: {
                      id: "NDateInput_YCIwil",
                      name: "NDateInput_YCIwil",
                      label: "出生日期",
                      readonly: false,
                      required: false,
                      hidden: false,
                      format: "YYYY-MM-DD",
                      sourceFormat: "YYYY-MM-DD",
                      labelAlign: "right",
                      valueAlign: "center",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                  {
                    text: "NLovInput",
                    name: "NLovInput",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNLovInput",
                    groupName: "nform",
                    id: "NLovInput_rzTppp",
                    attributes: {
                      id: "NLovInput_rzTppp",
                      name: "NLovInput_rzTppp",
                      label: "爱好",
                      autoComplete: true,
                      readonly: false,
                      required: false,
                      hidden: false,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                  {
                    text: "NMultiLineText",
                    name: "NMultiLineText",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nformNMultiLineText",
                    groupName: "nform",
                    id: "NMultiLineText_VKiNzl",
                    attributes: {
                      id: "NMultiLineText_VKiNzl",
                      name: "NMultiLineText_VKiNzl",
                      label: "表单插入",
                      inputMaxLength: -1,
                      autoComplete: true,
                      readonly: false,
                      required: false,
                      hidden: false,
                      rows: 3,
                      labelAlign: "right",
                      valueAlign: "left",
                      fontBold: false,
                      underline: false,
                      oblique: false,
                      border: true,
                    },
                  },
                ],
              },
              {
                text: "NButtons",
                name: "NButtons",
                version: "1.0",
                implement: "mouseX",
                type: "PageNButtons",
                icon: "按钮容器",
                groupName: "page",
                id: "NButtons_tbWUdC",
                attributes: {
                  id: "NButtons_tbWUdC",
                  align: "right",
                  flexBasic: "need",
                  hidden: false,
                },
                children: [
                  {
                    text: "NButton",
                    name: "NButton",
                    version: "1.0",
                    implement: "mouseX",
                    type: "PageNButton",
                    groupName: "page",
                    id: "NButton_JEDgLN",
                    attributes: {
                      id: "NButton_JEDgLN",
                      label: "保存",
                      authId: "",
                      title: "",
                      iconId: "",
                      iconColor: "",
                      size: "middle",
                      type: "default",
                      danger: false,
                      ghost: false,
                      disabled: false,
                      hidden: false,
                    },
                  },
                  {
                    text: "NButton",
                    name: "NButton",
                    version: "1.0",
                    implement: "mouseX",
                    type: "PageNButton",
                    groupName: "page",
                    id: "NButton_VnhlaW",
                    attributes: {
                      id: "NButton_VnhlaW",
                      label: "取消",
                      authId: "",
                      title: "",
                      iconId: "",
                      iconColor: "",
                      size: "middle",
                      type: "default",
                      danger: false,
                      ghost: false,
                      disabled: false,
                      hidden: false,
                    },
                  },
                ],
              },
            ],
          },
          {
            groupName: "nquerytable",
            name: "nquerytable",
            implement: "mouseX",
            text: "NQueryTable",
            id: "actinsTable",
            type: "nquerytable",
            version: "1.0",
            attributes: {
              id: "actinsTable",
              batchMode: false,
              showRowNumber: true,
              filterable: false,
              flexBasic: "fill",
              marginRight: 10,
              marginBottom: 10,
              hidden: false,
            },
            children: [
              {
                groupName: "nquerytable",
                name: "Input",
                implement: "mouseX",
                text: "Input",
                id: "Input_VnNaur",
                type: "nquerytableInput",
                version: "1.0",
                attributes: {
                  id: "Input_VnNaur",
                  name: "actioniid",
                  head: "环节实例编号",
                  hidden: false,
                  width: 150,
                  widthFixed: true,
                  bodyAlign: "left",
                },
              },
              {
                groupName: "nquerytable",
                name: "Input",
                implement: "mouseX",
                text: "Input",
                id: "Input_ixZQgY",
                type: "nquerytableInput",
                version: "1.0",
                attributes: {
                  id: "Input_ixZQgY",
                  name: "exe_id",
                  head: "运行实例编号",
                  hidden: false,
                  width: 150,
                  widthFixed: true,
                  bodyAlign: "left",
                },
              },
              {
                groupName: "nquerytable",
                name: "Input",
                implement: "mouseX",
                text: "Input",
                id: "Input_Nsvomw",
                type: "nquerytableInput",
                version: "1.0",
                attributes: {
                  id: "Input_Nsvomw",
                  name: "actionlabel",
                  head: "环节名称",
                  hidden: false,
                  widthFixed: false,
                  bodyAlign: "left",
                },
              },
              {
                groupName: "nquerytable",
                name: "Input",
                implement: "mouseX",
                text: "Input",
                id: "Input_LrRxmv",
                type: "nquerytableInput",
                version: "1.0",
                attributes: {
                  id: "Input_LrRxmv",
                  name: "token",
                  head: "运行结果",
                  hidden: false,
                  widthFixed: false,
                  bodyAlign: "left",
                },
              },
              {
                groupName: "nquerytable",
                name: "DatePicker",
                implement: "mouseX",
                text: "DatePicker",
                id: "DatePicker_xvDWsY",
                type: "nquerytableDatePicker",
                version: "1.0",
                attributes: {
                  id: "DatePicker_xvDWsY",
                  name: "end_time",
                  head: "结束时间",
                  hidden: false,
                  widthFixed: false,
                  format: "YYYY-MM-DD HH:mm:ss.SSS",
                  sourceFormat: "YYYY-MM-DD HH:mm:ss.SSS",
                  bodyAlign: "center",
                },
              },
              {
                text: "PicButtons",
                name: "NButtons",
                version: "1.0",
                implement: "mouseX",
                type: "nquerytableNButtons",
                groupName: "nquerytable",
                id: "NButtons_pblhpQ",
                attributes: {
                  id: "NButtons_pblhpQ",
                  name: "NButtons_pblhpQ",
                  head: "表格插入",
                  hidden: false,
                  widthFixed: false,
                  bodyAlign: "center",
                },
                children: [
                  {
                    text: "PicButton",
                    name: "NButton",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nquerytableNButton",
                    groupName: "nquerytable",
                    id: "NButton_YzJwPx",
                    attributes: {
                      id: "NButton_YzJwPx",
                      name: "NButton_YzJwPx",
                      label: "按钮",
                      iconId: "",
                      iconColor: "",
                      disabled: false,
                      hidden: false,
                      danger: false,
                    },
                  },
                  {
                    text: "PicButton",
                    name: "NButton",
                    version: "1.0",
                    implement: "mouseX",
                    type: "nquerytableNButton",
                    groupName: "nquerytable",
                    id: "NButton_RhisFR",
                    attributes: {
                      id: "NButton_RhisFR",
                      name: "NButton_RhisFR",
                      label: "按钮",
                      iconId: "",
                      iconColor: "",
                      disabled: false,
                      hidden: false,
                      danger: false,
                    },
                  },
                ],
              },
              {
                groupName: "nquerytable",
                name: "NButtons",
                implement: "mouseX",
                text: "PicButtons",
                id: "NButtons_DsLZPC",
                type: "nquerytableNButtons",
                version: "1.0",
                attributes: {
                  id: "NButtons_DsLZPC",
                  name: "NButtons_DsLZPC",
                  head: "日志",
                  hidden: false,
                  width: 80,
                  widthFixed: true,
                  bodyAlign: "center",
                },
                children: [
                  {
                    groupName: "nquerytable",
                    name: "NButton",
                    implement: "mouseX",
                    text: "PicButton",
                    id: "NButton_NHQKOy",
                    type: "nquerytableNButton",
                    version: "1.0",
                    attributes: {
                      id: "NButton_NHQKOy",
                      name: "NButton_NHQKOy",
                      label: "查看",
                      iconId: "",
                      iconColor: "",
                      disabled: false,
                      hidden: false,
                      danger: false,
                      onClick: "viewProcessTaskRunLog",
                    },
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  pagefunction:
    'async function generateData() {\r\n    const params = Cabin.getParams();\r\n    const { eventiid } = params;\r\n\r\n    const piinfo = Cabin.getNFormInstance("piinfo");\r\n\r\n    const actinsTable = Cabin.getNQueryTableInstance("actinsTable");\r\n\r\n    const result = await Cabin.post("/manage/getEventIHawkPi",{eventiid});\r\n\r\n    piinfo.setData(result.piinfo);\r\n\r\n    actinsTable.setData(result.actins);\r\n\r\n    console.log(result.actins);\r\n\r\n}\r\n\r\nasync function runPI() {\r\n    const params = Cabin.getParams();\r\n    const { eventiid } = params;\r\n\r\n    const piinfo = Cabin.getNFormInstance("piinfo");\r\n\r\n    const piInfoData = piinfo.getData();\r\n\r\n    const status = piInfoData.status;\r\n\r\n    if(status && status==0){\r\n        Cabin.NMsgBox.warn("流程已经结束，不允许再次触发执行。");\r\n        return;\r\n    }\r\n\r\n\r\n    await Cabin.post("/manage/runPi",{eventiid});\r\n\r\n    generateData();\r\n\r\n    Cabin.NMsgBox.success("再次触发执行，刷新状态监控运行结果");\r\n}\r\n\r\nasync function viewProcessTaskRunLog(){\r\n    const params = Cabin.getParams();\r\n    const table = Cabin.getNQueryTableInstance(\'actinsTable\');\r\n    const rowData = table.getData().getRowData(table.getCurrentRow());\r\n    Cabin.NModal.open({cabinName:\'viewProcessTaskRunLog\',params:{...params,...rowData}})\r\n}',
};
